language: node_js
node_js:
  - "stable"
env:
  global:
    - CC_TEST_REPORTER_ID=0c9114bfd41a18b4567df3b67f2833971df5ad408170831d92c6433afbc453a6
    - NODE_ENV=test
services:
  - postgresql
before_script:
script: npm run test
